
setup.template.settings:                                                                                                                                              
  index:
    number_of_shards: 1
    number_of_replicas: 0
    codec: best_compression

auditbeat.modules:

- module: auditd
  audit_rules: |
    -w /etc/passwd -p wa -k identity
    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access
- module: file_integrity
  paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc

processors:
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.dashboards.enabled: true
setup.kibana.host: '${KIBANA_HOST:kibana:5601}'

http.enabled: true
http.host: 0.0.0.0
http.port: 5066

#logging.level: debug
