metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

setup.template.settings:
  index:
    number_of_shards: 1
    number_of_replicas: 0
    codec: best_compression

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: system
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - socket_summary  # Socket summary
    - core           # Per CPU core usage
    - diskio         # Disk IO
    - filesystem     # File system usage for each mountpoint
    - fsstat         # File system summary metrics
    - socket         # Sockets and connection info (linux only)
  enabled: true
  period: 10s
  processes: ['.*']

  # Configure the metric types that are included by these metricsets.
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory: 
  cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
  core.metrics: ["percentages"]  # The other available option is ticks.

- module: elasticsearch
  metricsets:
    - ccr
    - cluster_stats
    - index
    - index_recovery
    - index_summary
    - ml_job
    - node_stats
    - shard
    - enrich
  period: 10s
  hosts: "${ELASTICSEARCH_HOSTS:elasticsearch:9200}"
  username: "${ELASTICSEARCH_USERNAME:}" 
  password: "${ELASTICSEARCH_PASSWORD:}"
  enabled: true
  xpack.enabled: true

- module: kibana
  metricsets: ["status","stats"]
  period: 10s
  hosts: ["kibana:5601"]
  username: "${ELASTICSEARCH_USERNAME:}" 
  password: "${ELASTICSEARCH_PASSWORD:}"
  enabled: true
  xpack.enabled: true

- module: logstash
  enabled: true
  xpack.enabled: true
  metricsets:
    - node
    - node_stats
  period: 10s
  hosts: ["logstash:9600"]

- module: appsearch
  metricsets: ["stats"]
  enabled: true
  period: 10s
  hosts: ["http://app-search:3002"]

- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts: 
    - "http://metricbeat:5066"
    - "http://heartbeat:5066"
    - "http://filebeat:5066"
    - "http://packetbeat:5066"
    - "http://journalbeat:5066"
    - "http://auditbeat:5066"
    - "http://apmserver:5066"
  enabled: true
  xpack.enabled: true


processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.dashboards.enabled: true
setup.kibana.host: '${KIBANA_HOST:kibana:5601}'

http.enabled: true
http.host: 0.0.0.0
http.port: 5066
