version: '3'
services:
  redis:
    container_name: redis
    image: redis:3.2
    volumes:
      - "./redis_data:/data"
      - "/etc/localtime:/etc/localtime"
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --requirepass 1233456 --appendonly yes